---
name: cooljeanius/ManDrake
on:
  push:
    branches:
      - "**/*"
      - master
  pull_request:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '14.3.1'
      - name: Set up cocoapods cache
        uses: actions/cache@v4.2.0
        with:
          path: Pods
          key: "${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}"
          restore-keys: "${{ runner.os }}-pods-"
      - run: gem install xcpretty
      - run: pod update
      - run: ./build.sh
