name: cooljeanius/ManDrake
on:
  push:
    branches:
    - "**/*"
    - master
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '11.4'
    - name: Set up cocoapods cache
      uses: actions/cache@v3.3.1
      with:
        path: Pods
        key: "${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}"
        restore-keys: "${{ runner.os }}-pods-"
    - run: gem install xcpretty
    - run: pod update
    - run: pods install
    - run: cd ManDrake/cat2html && ./build_cat2html.sh
    - run: cd ../.. && ./build.sh
